### ISSUE TITLE
selecting the file in browser with a will open the file

### ISSUE THREAD

**Issue by prajwalrajup** [ElecTreeFrying/auto-import-relative-path#2]
when I select the file in browser with a will open the file and does not allow me to copy the file 
and when I do copy the file location and paste in the .jxs file it shows an invalid import

**Comment by iaeiou** [comment]
I have the same problem to insert image in a Markdown file. Here is my workaround:

- I click on the file I want to insert
- The file is open
- I use the command "Auto import: copy"
- I close the file and go back to my Markdown file
- I use the command "Auto import: paste"

**Comment by iaeiou** [comment]
That's an awesome extension for Markdown writers @ElecTreeFrying , you should advertise this feature more!
Anyway, thanks a lot!

**Comment by ElecTreeFrying** [comment]
> when I select the file in browser with a will open the file and does not allow me to copy the file and when I do copy the file location and paste in the .jxs file it shows an invalid import

Unfortunately, we do not currently have support for this specific issue as it may be related to how the web browser handles file links and how the file location is being copied and pasted into the .jsx file.

If you have any further questions or concerns, please reopen the issue. Thanks.
