### ISSUE TITLE
Default Keyboard-Shortcut for auto-import-copy does not work on Mac

### ISSUE THREAD

**Issue by mj-h** [ElecTreeFrying/auto-import-relative-path#6]
The keyboard-shortcut for the auto-import-copy command does not work on Mac. The keybinding on a fresh installation is empty: 

![image](https://user-images.githubusercontent.com/20513065/138113241-b9d64b25-6cbc-43d8-b52c-06d665bd0b1b.png)

I suspect this is related to an extra `+`-sign in [this line](https://github.com/ElecTreeFrying/auto-import-relative-path/blob/aa0abd165b399f85e186e25b3b52f6628cc38a1e/package.json#L73):

```
"mac": "cmd++shift+a",
```

**Comment by ElecTreeFrying** [comment]
I wanted to reach out and let you know that the issue you reported has already been resolved in the latest version of the extension. I would recommend updating the extension to the latest version to ensure that you have the most up-to-date features and bug fixes.

**Comment by ElecTreeFrying** [comment]
if you still need assistance or if the issue persists, please don't hesitate to reopen it or create a new one.
