### ISSUE TITLE
The setting "importStatements.markdown.markdownImageSupport" does not exist in the UI

### ISSUE THREAD

**Issue by iaeiou** [ElecTreeFrying/auto-import-relative-path#7]
Hi there!

This extension works fine with Markdown (thanks a lot!), and I would like to customize the settings.

The doc says that [two settings are available](https://github.com/ElecTreeFrying/auto-import-relative-path#import-statements--markdown).

I can't find them in the UI (accessed with `Ctrl + ,`), even if I just search for `import` or `statement`.
Some settings related to Auto import Typescript / Javascript can't be found though

Do you have any hints?

Vscode details:
```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-17T00:20:01.675Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 4.19.0-17-amd64
```

**Comment by ElecTreeFrying** [comment]
I wanted to reach out and let you know that the issue you reported has already been resolved in the latest version of the extension. I would recommend updating the extension to the latest version to ensure that you have the most up-to-date features and bug fixes.

**Comment by ElecTreeFrying** [comment]
if you still need assistance or if the issue persists, please don't hesitate to reopen it or create a new one.
